language: objective-c
osx_image: xcode8.1
script:
    - xcodebuild -workspace PayfortStart.xcworkspace -scheme Demo -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO
    - xcodebuild -workspace PayfortStart.xcworkspace -scheme DemoSwift -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO
    - xcodebuild -workspace PayfortStart.xcworkspace -scheme StartSDK -configuration Release -sdk iphonesimulator10.1 -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.1' test
